

=== ERROR IN PLANNER_PREPROCESSING_AGENT ===
Error in planner_preprocessing_agent: cannot do positional indexing on RangeIndex with these indexers [33.0] of type float
Traceback (most recent call last):
  File "D:\Firebird2\Auto-Analyst-CS\auto-analyst-backend\scripts\format_response.py", line 196, in execute_code_from_markdown
    exec(block_code, context)  # Execute the block

Problem at this location:
1: 
2: >>> print(df.head(33.)) <<<
3: 
4: # planner_preprocessing_agent code end

Full error details:
  File "D:\Firebird2\Auto-Analyst-CS\auto-analyst-backend\venv\Lib\site-packages\pandas\core\indexes\base.py", line 4301, in _raise_invalid_indexer
    raise TypeError(msg)
TypeError: cannot do positional indexing on RangeIndex with these indexers [33.0] of type float


=== ERROR IN PREPROCESSING_AGENT ===
Error in preprocessing_agent: cannot do positional indexing on RangeIndex with these indexers [33.33] of type float
Traceback (most recent call last):
  File "D:\Firebird2\Auto-Analyst-CS\auto-analyst-backend\scripts\format_response.py", line 196, in execute_code_from_markdown
    exec(block_code, context)  # Execute the block

Problem at this location:
1: 
2: >>> print(df.head(33.33)) <<<
3: 
4: # preprocessing_agent code end

Full error details:
  File "D:\Firebird2\Auto-Analyst-CS\auto-analyst-backend\venv\Lib\site-packages\pandas\core\indexes\base.py", line 4301, in _raise_invalid_indexer
    raise TypeError(msg)
TypeError: cannot do positional indexing on RangeIndex with these indexers [33.33] of type float


=== ERROR IN PLANNER_AGENT ===
Error in planner_agent: NDFrame.head() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "D:\Firebird2\Auto-Analyst-CS\auto-analyst-backend\scripts\format_response.py", line 196, in execute_code_from_markdown
    exec(block_code, context)  # Execute the block

Problem at this location:
1: 
2: >>> print(df.head(32,3)) <<<
3: 
4: # planner_agent code end

Full error details:
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in <module>
TypeError: NDFrame.head() takes from 1 to 2 positional arguments but 3 were given


=== ERROR IN STATS_AGENT ===
Error in stats_agent: 'tuple' object is not callable
Traceback (most recent call last):
  File "D:\Firebird2\Auto-Analyst-CS\auto-analyst-backend\scripts\format_response.py", line 196, in execute_code_from_markdown
    exec(block_code, context)  # Execute the block

Problem at this location:
1: 
2: >>> print(df.shape(3)) <<<
3: 
4: # stats_agent code end

Full error details:
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in <module>
TypeError: 'tuple' object is not callable